# Generated by Django 5.0.6 on 2026-03-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studistics', '0002_exam_revisionlog_studysession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='marks_scored',
        ),
        migrations.AddField(
            model_name='studysession',
            name='practice_score',
            field=models.FloatField(blank=True, help_text='Score from practice test or self-assessment (e.g. 7 out of 10, enter 7)', null=True),
        ),
    ]
