# Generated by Django 5.0.6 on 2026-03-22 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studistics', '0003_remove_studysession_marks_scored_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='practice_score',
            field=models.FloatField(blank=True, help_text='Score as a percentage (0 to 100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='study_time',
            field=models.PositiveIntegerField(help_text='Minutes studied', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
