# Generated by Django 5.0.6 on 2026-03-22 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studistics', '0004_alter_studysession_practice_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='study_time',
            field=models.FloatField(help_text='Hours studied (e.g., 0.5, 1.5)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
